title: KJH의 기술블로그
description: "도메인 구조 개선, 무중단 마이그레이션, 개발 생산성 향상 경험을 기록하는 공간입니다."
url: "https://kjh-sun.github.io"
baseurl: "/juhyun-tech-blog"
lang: ko
email: "juhyun7955@gmail.com"
theme: minima
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
plugins:
  - jekyll-feed
  - jekyll-seo-tag
header_pages:
  - about.md
minima:
  date_format: "%Y-%m-%d"
author: 김주현
